import { defineConfig } from "orval";

// Generates typed TanStack Query hooks and MSW mock handlers from the backend's OpenAPI spec.
// Run `npm run api:generate` after `npm run api:sync`; never edit src/api/generated by hand.
export default defineConfig({
  tennis: {
    input: { target: "./api/openapi.json" },
    output: {
      mode: "tags-split",
      target: "./src/api/generated/endpoints",
      schemas: "./src/api/generated/model",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      mock: { generators: [{ type: "msw", delay: false }] },
      override: {
        mutator: { path: "./src/api/http.ts", name: "apiFetch" },
        fetch: { includeHttpResponseReturnType: false },
        query: { signal: true },
      },
    },
  },
});
